accessory:
  id: nibe-
  services:
    - type: AccessoryInformation
      characteristics:
        - type: Manufacturer
          value: Nibe
        - type: Model
          id: 1
          attribute: displayValue
        - type: SerialNumber
          id: 2
          attribute: displayValue
accessoriesConfiguration:
  - id: average-outdoor-temperature
    name: average-outdoor-temperature
    services:
      - type: TemperatureSensor
        characteristics:
          - type: CurrentTemperature
            id: 40067
            refresh: true
          - type: Name
            value: temperature.average.name
            translate: true
  - id: outdoor-temperature-40004
    name: outdoor-temperature
    services:
      - type: TemperatureSensor
        characteristics:
          - type: CurrentTemperature
            id: 40004
            refresh: true
          - type: Name
            value: temperature.current.name
            translate: true
  - id: outdoor-temperature-44362
    name: outdoor-temperature
    services:
      - type: TemperatureSensor
        characteristics:
          - type: CurrentTemperature
            id: 44362
            refresh: true
          - type: Name
            value: temperature.current.name
            translate: true
      - type: AccessoryInformation
        characteristics:
          - type: SerialNumber
            value: "00000000"
  - id: hot-water-top
    name: hot-water-top
    services:
      - type: TemperatureSensor
        characteristics:
          - type: CurrentTemperature
            id: 40013
            refresh: true
          - type: Name
            value: temperature.top.name
            translate: true
  - id: hot-water
    name: hot-water
    services:
      - type: HeaterCooler
        characteristics:
          - type: CurrentTemperature
            id: 40014
            refresh: true
          - type: Active
            id: 48132
            refresh: true
            manage:
              id: 48132
          - type: CurrentHeaterCoolerState
            id: 43115
            attribute: displayValue
            refresh: true
            parser: notEmpty
            mapper:
              - true: 2
              - false: 1
            props:
              maxValue: 2
              minValue: 1
              validValues: [1, 2]
          - type: TargetHeaterCoolerState
            value: 0
            props:
              maxValue: 0
              minValue: 0
              validValues: [0]
          - type: TemperatureDisplayUnits
            id: 40014
            attribute: unit
            mapper:
              - "°F": 1
              - "default": 0
            props:
              perms: ["pr"]
            refresh: true
          - type: Name
            value: temperature.current.name
            translate: true
          - type: HeatingThresholdTemperature
            config:
              key: temporaryLuxMaxTemperature
              default: 53
            props:
              maxValue: 70
            refresh: true
  - id: ers-exhaust-air
    name: ers-exhaust-air
    services:
      - type: TemperatureSensor
        characteristics:
          - type: CurrentTemperature
            id: 40025
            refresh: true
          - type: Name
            value: temperature.name
            translate: true
  - id: ers-extract-air
    name: ers-extract-air
    services:
      - type: TemperatureSensor
        characteristics:
          - type: CurrentTemperature
            id: 40026
            refresh: true
          - type: Name
            value: temperature.name
            translate: true
  - id: ers-supply-air
    name: ers-supply-air
    services:
      - type: TemperatureSensor
        characteristics:
          - type: CurrentTemperature
            id: 40075
            refresh: true
          - type: Name
            value: temperature.name
            translate: true
  - id: ers-outdoor
    name: ers-outdoor
    services:
      - type: TemperatureSensor
        characteristics:
          - type: CurrentTemperature
            id: 40183
            refresh: true
          - type: Name
            value: temperature.name
            translate: true
  - id: ers-fan
    name: ers-fan
    services:
      - type: Fanv2
        characteristics:
          - type: Active
            provider:
              name: MaxValue
              params:
                ids: [40311, 40312]
            refresh: true
            parser: graterThan0
            mapper:
              - true: 1
              - false: 0
            props:
              perms: ["pr"]
          - type: CurrentFanState
            provider:
              name: MaxValue
              params:
                ids: [40311, 40312]
            refresh: true
            parser: graterThan0
            mapper:
              - true: 2
              - false: 1
          - type: RotationSpeed
            provider:
              name: MaxValue
              params:
                ids: [40311, 40312]
            refresh: true
            manage:
              id: 47260
              provider:
                name: ErsRotationSpeedStepSetter
                params:
                  ids: [40311, 40312]
          - type: Name
            value: fan.name
            translate: true
