accessories:
  - id: outdoor-temperature
    services:
      - type: TemperatureSensor
        characteristics:
          - type: CurrentTemperature
            id: 40004
            refresh: true
          - type: Name
            value: temperature.current.name
            translate: true