name: reviewdog
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'src/'
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          locale: "UK"
          pattern: |
            *.ts
            *.yml
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: github-pr-review
          level: warning
      - uses: reviewdog/action-languagetool@v1
        with:
          reporter: github-pr-review
          level: info
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: github-pr-review
          level: warning
      - uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-pr-review
      - uses: reviewdog/action-actionlint@v1
